#!/bin/zsh

source ~/.theme_env_vars

# pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width 2 
bspc config window_gap 12
bspc config focused_border_color $THEME_PRIMARY

bash $HOME/.config/bspwm/scripts/autostart.sh
